pipeline {
  agent any

  environment {
    AWS_REGION = 'us-east-1'
    CLUSTER_NAME = 'cicd-eks-cluster'
    RELEASE_NAME = 'user-service'
    NAMESPACE = 'default'
    CHART_PATH = 'helm/user-service'
  }

  stages {
    stage('Test') {
      steps {
        sh '''
          cd microservices/user-service
          python3 -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
          pytest
        '''
      }
    }

    stage('Build') {
      steps {
        sh 'docker build -t $ECR_URI:$BUILD_NUMBER microservices/user-service'
      }
    }

    stage('Push') {
      steps {
        sh '''
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin ${ECR_URI%/*}
          docker push $ECR_URI:$BUILD_NUMBER
        '''
      }
    }

    stage('Deploy') {
      steps {
        sh '''
          aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION
          helm upgrade --install $RELEASE_NAME $CHART_PATH \
            --namespace $NAMESPACE \
            --create-namespace \
            --set image.repository=$ECR_URI \
            --set image.tag=$BUILD_NUMBER \
            --set env.VERSION=$BUILD_NUMBER \
            --atomic \
            --wait \
            --timeout 10m
        '''
      }
    }
  }
}
