apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-service.fullname" . }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "user-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-service.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
      containers:
        - name: user-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: PROJECT_NAME
              value: {{ .Values.env.PROJECT_NAME | quote }}
            - name: SERVICE_NAME
              value: {{ .Values.env.SERVICE_NAME | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.env.ENVIRONMENT | quote }}
            - name: VERSION
              value: {{ .Values.env.VERSION | quote }}
            - name: IMAGE_TAG
              value: {{ .Values.env.IMAGE_TAG | quote }}
            - name: GIT_COMMIT
              value: {{ .Values.env.GIT_COMMIT | quote }}
            - name: BUILD_DATE
              value: {{ .Values.env.BUILD_DATE | quote }}
            - name: AWS_REGION
              value: {{ .Values.env.AWS_REGION | quote }}
            - name: CLUSTER_NAME
              value: {{ .Values.env.CLUSTER_NAME | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
